### ISSUE TITLE
Ember-sortable 4.0.0 crashes during build on ember-modifier

### ISSUE THREAD

**Issue by IgnaceMaes** [adopted-ember-addons/ember-sortable#481]
**Describe the bug**

When upgrading from `ember-sortable@3.0.1` to `ember-sortable@4.0.0` the following issue occurs during the build. Any idea what could be the cause here?

**To Reproduce**

Environment:
- Ember v3.28
- Node.js v14.19.1
- ember-sortable v4.0.0

Running `ember serve` results in the error at the bottom of this issue.

**Expected behavior**

The build to succeed. According to the README/CHANGELOG the versions of ember/node should be compatible.

**Screenshots**

/

**Additional context**

```
ERROR Summary:

  - broccoliBuilderErrorStack: SyntaxError: <REDACTED>/ember-modifier/-private/function-based/modifier.ts: Missing semicolon (37:10)

  35 | // value from a `modifier()` call.
  36 | export type FunctionBasedModifier<S> =
> 37 |   abstract new () => FunctionBasedModifierInstance<S>;
     |           ^
  38 |
  39 | /**
  40 |  * The (optional) return type for a modifier which needs to perform some kind of
    at Object._raise (<REDACTED>/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:776:17)
    at Object.raiseWithData (<REDACTED>/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:769:17)
    at Object.raise (<REDACTED>/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:737:17)
    at Object.semicolon (<REDACTED>/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:9165:10)
    at Object.tsParseTypeAliasDeclaration (<REDACTED>/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:6176:10)
    at Object.tsParseDeclaration (<REDACTED>/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:6498:23)
    at Object.tsTryParseExportDeclaration (<REDACTED>/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:6403:17)
    at Object.parseExportDeclaration (<REDACTED>/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:6973:26)
    at Object.maybeParseExportDeclaration (<REDACTED>/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:12946:31)
    at Object.parseExport (<REDACTED>/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:12884:29)
  - code: [undefined]
  - codeFrame: <REDACTED>/ember-modifier/-private/function-based/modifier.ts: Missing semicolon (37:10)

  35 | // value from a `modifier()` call.
  36 | export type FunctionBasedModifier<S> =
> 37 |   abstract new () => FunctionBasedModifierInstance<S>;
     |           ^
  38 |
  39 | /**
  40 |  * The (optional) return type for a modifier which needs to perform some kind of
  - errorMessage: ember-modifier/-private/function-based/modifier.ts: <REDACTED>/ember-modifier/-private/function-based/modifier.ts: Missing semicolon (37:10)

  35 | // value from a `modifier()` call.
  36 | export type FunctionBasedModifier<S> =
> 37 |   abstract new () => FunctionBasedModifierInstance<S>;
     |           ^
  38 |
  39 | /**
  40 |  * The (optional) return type for a modifier which needs to perform some kind of
        in /var/folders/9h/5lcgcj596r94wnt0shgmjdjc0000gp/T/broccoli-281835QSMOpGE670Q/out-499-funnel
        at broccoli-persistent-filter:Babel > [Babel: ember-modifier] (Babel: ember-modifier)
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: ember-modifier/-private/function-based/modifier.ts
    - line: [undefined]
    - treeDir: /var/folders/9h/5lcgcj596r94wnt0shgmjdjc0000gp/T/broccoli-281835QSMOpGE670Q/out-499-funnel
  - message: ember-modifier/-private/function-based/modifier.ts: <REDACTED>/ember-modifier/-private/function-based/modifier.ts: Missing semicolon (37:10)

  35 | // value from a `modifier()` call.
  36 | export type FunctionBasedModifier<S> =
> 37 |   abstract new () => FunctionBasedModifierInstance<S>;
     |           ^
  38 |
  39 | /**
  40 |  * The (optional) return type for a modifier which needs to perform some kind of
        in /var/folders/9h/5lcgcj596r94wnt0shgmjdjc0000gp/T/broccoli-281835QSMOpGE670Q/out-499-funnel
        at broccoli-persistent-filter:Babel > [Babel: ember-modifier] (Babel: ember-modifier)
  - name: Error
  - nodeAnnotation: Babel: ember-modifier
  - nodeName: broccoli-persistent-filter:Babel > [Babel: ember-modifier]
  - originalErrorMessage: <REDACTED>/ember-modifier/-private/function-based/modifier.ts: Missing semicolon (37:10)

  35 | // value from a `modifier()` call.
  36 | export type FunctionBasedModifier<S> =
> 37 |   abstract new () => FunctionBasedModifierInstance<S>;
     |           ^
  38 |
  39 | /**
  40 |  * The (optional) return type for a modifier which needs to perform some kind of
  - stack: SyntaxError: <REDACTED>/ember-modifier/-private/function-based/modifier.ts: Missing semicolon (37:10)

  35 | // value from a `modifier()` call.
  36 | export type FunctionBasedModifier<S> =
> 37 |   abstract new () => FunctionBasedModifierInstance<S>;
     |           ^
  38 |
  39 | /**
  40 |  * The (optional) return type for a modifier which needs to perform some kind of
    at Object._raise (<REDACTED>/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:776:17)
    at Object.raiseWithData (<REDACTED>/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:769:17)
    at Object.raise (<REDACTED>/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:737:17)
    at Object.semicolon (<REDACTED>/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:9165:10)
    at Object.tsParseTypeAliasDeclaration (<REDACTED>/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:6176:10)
    at Object.tsParseDeclaration (<REDACTED>/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:6498:23)
    at Object.tsTryParseExportDeclaration (<REDACTED>/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:6403:17)
    at Object.parseExportDeclaration (<REDACTED>/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:6973:26)
    at Object.maybeParseExportDeclaration (<REDACTED>/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:12946:31)
    at Object.parseExport (<REDACTED>/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:12884:29)

=================================================================================

```

**Comment by bertdeblock** [comment]
Is this a duplicate of https://github.com/ember-modifier/ember-modifier/issues/464?

**Comment by knownasilya** [comment]
Still an issue with latest v4.0.3?

**Comment by IgnaceMaes** [comment]
@bertdeblock It is. I've opened the issue there as well as the code that throws the error originates from `ember-modifier`. It was unclear to me if the fix should come from this package or that one.

@knownasilya Unfortunately, yes, it still gives the same error on v4.0.3. For now pinning the resolution of `ember-modifier` in `package.json` to the version before the one that introduced that syntax fixes it for me:

```json
"resolutions": {
  "ember-modifier": "3.2.2"
}
```

**Comment by knownasilya** [comment]
Looks like ember-modifier ships ts? Did you open a ticket there?
